name: my_test_app
description: A new Flutter project.
publish_to: 'none'
# ØªÙ… ØªØ­Ø¯ÙŠØ« Ø§Ù„Ø¥ØµØ¯Ø§Ø± Ù„ÙŠÙƒÙˆÙ† Build 3 Ø¬Ø§Ù‡Ø² Ù„Ù„Ø±ÙØ¹ Ø§Ù„Ù†Ù‡Ø§Ø¦ÙŠ
version: 1.0.2+13

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core packages
  http: ^1.2.2
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_messaging: ^16.0.4

  # Tables & UI
  data_table_2: ^2.5.9
  font_awesome_flutter: ^10.7.0
  intl: ^0.20.2
  fl_chart: ^1.1.1
  sizer: ^3.1.3

  # Printing & PDF
  pdf: ^3.11.3
  printing: ^5.11.1
  open_filex: ^4.3.2

  # Export to Excel
  excel: ^4.0.6
  share_plus: ^10.1.4
  path_provider: ^2.1.3
  permission_handler: ^12.0.1
  universal_html: ^2.2.0

  # State management & utilities
  provider: ^6.1.2
  geolocator: ^14.0.2
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.3

  # Marketing & Tracking
  facebook_app_events: ^0.24.0

  # Fonts
  google_fonts: ^6.1.0

  # Material 3 & icons
  dynamic_color: ^1.8.1
  material_design_icons_flutter: ^7.0.7296
  lucide_icons: ^0.257.0

  # Images & network
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7

  # Geocoding & maps
  geocoding: ^4.0.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  flutter_map_geojson: ^1.0.3
  flutter_local_notifications: ^19.5.0
  firebase_crashlytics: ^5.0.7
  firebase_analytics: ^12.1.2
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # Ø£Ø¯ÙˆØ§Øª ØªÙˆÙ„ÙŠØ¯ Ø§Ù„Ø£ÙŠÙ‚ÙˆÙ†Ø§Øª ÙˆØ§Ù„Ù€ Splash
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

# ðŸš€ Ø¥Ø¹Ø¯Ø§Ø¯Ø§Øª Ø§Ù„Ø£ÙŠÙ‚ÙˆÙ†Ø© Ø§Ù„Ø§Ø­ØªØ±Ø§ÙÙŠØ© (Ø®Ù„ÙÙŠØ© Ø¨ÙŠØ¶Ø§Ø¡)
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/flutter_logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/flutter_logo.png"
  adaptive_icon_foreground_inset: 0

# ðŸš€ Ø¥Ø¹Ø¯Ø§Ø¯Ø§Øª Ø´Ø§Ø´Ø© Ø§Ù„Ø§ÙØªØªØ§Ø­ÙŠØ© (Ù„Ù…Ù†Ø¹ Ø§Ù„Ø±Ù…Ø´Ø© Ø§Ù„Ø³ÙˆØ¯Ø§Ø¡)
flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/flutter_logo.png"
  android_12:
    image: "assets/flutter_logo.png"
    color: "#FFFFFF"
  fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

