name: Build Flutter APK (Fast Release)

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ§© Checkout Code
        uses: actions/checkout@v4

      - name: â˜•ï¸ Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: ğŸ”§ Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: ğŸ“¦ Install Dependencies
        run: flutter pub get

      - name: ğŸ”‘ Decode aksab_new.keystore
        env:
          RELEASE_KEYSTORE_BASE64: ${{ secrets.RELEASE_KEYSTORE_BASE64 }}
        run: |
          # ÙÙƒ ØªØ´ÙÙŠØ± Ø§Ù„Ù…ÙØªØ§Ø­ Ø§Ù„Ø¬Ø¯ÙŠØ¯ ÙÙŠ Ø§Ù„Ù…Ø³Ø§Ø± Ø§Ù„ØµØ­ Ø¯Ø§Ø®Ù„ Ù…Ø¬Ù„Ø¯ app
          echo "$RELEASE_KEYSTORE_BASE64" | base64 --decode > android/app/aksab_new.keystore

      - name: ğŸ—ï¸ Build Release APK
        env:
          # Ø±Ø¨Ø· Ø§Ù„Ø¨ÙŠØ¦Ø© Ø¨Ø§Ù„Ø³ÙŠÙƒØ±ÙŠØªØ§Øª Ø§Ù„Ø¬Ø¯ÙŠØ¯Ø© Ø§Ù„Ù„ÙŠ Ø­Ø·ÙŠÙ†Ø§Ù‡Ø§ ÙÙŠ Ø¬ÙŠØª Ù‡ÙˆØ¨
          KEYSTORE_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.ALIAS_NAME }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD_ALIAS }}
        run: |
          # Ø¥Ù†Ø´Ø§Ø¡ Ù…Ù„Ù key.properties Ù…Ø¤Ù‚ØªØ§Ù‹ Ø¹Ø´Ø§Ù† Ø§Ù„Ø¬Ø±ÙŠØ¯Ù„ ÙŠØ´ÙˆÙ Ø§Ù„Ù…ÙØ§ØªÙŠØ­
          echo "storePassword=$KEYSTORE_PASSWORD" > android/key.properties
          echo "keyPassword=$KEY_PASSWORD" >> android/key.properties
          echo "keyAlias=$KEY_ALIAS" >> android/key.properties
          echo "storeFile=aksab_new.keystore" >> android/key.properties
          
          flutter build apk --release

      - name: ğŸ“¤ Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: aksab-signed-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: ğŸ” Show SHA Fingerprints
        run: |
          cd android
          chmod +x gradlew
          ./gradlew signingReport

